platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'YUniMPSDKDome' do
  pod 'YUniMPSDK', '~> 3.8', :modular_headers => true
  pod 'YUniMPSDK/BaiduSDK','~> 3.8',:modular_headers => true
end
